### PR TITLE
don't init buffers if ready for capture

### PR DESCRIPTION
**Pull request by TadayukiOkada**
This is related to #310 

I was able to capture video from multiple gst-launch commands on a v4l2loopback device, but when I stop one of them, it also crushes others.
It seems GStreamer calls VIDIOC_REQBUFS with buffer count 0 when it stops and that re-init buffers in the v4l2loopback device. That seems to crush other clients.

I just moved init_buffers() in vidioc_reqbufs() after checking buffer count is less than 0 and also added test for ready_for_capture.
This seems to fix the issue with GStreamer calling VIDIOC_REQBUFS when stops.
(Actually, testing ready_for_capture is unnecessary just to fix my issue, I suppose.)

It might be better to return EBUSY if ready_for_capture and don't manipulate the buffer list at all in that case. But that could break things, maybe?

### CODE REVIEW

**Comment by bmghirbi** [comment]
I had the same issue and this got me thinking: why not simply remove the call `init_buffers` in the function `vidioc_reqbufs`.
The `init_buffers()` is already called when buffers are allocated. So, technically, buffers are already initialized when the call `vidioc_reqbufs` is made. Could be that I am missing something ?

**Comment by vicamo** [comment]
Note, this (multiple capturing) is not allowed by a compliant V4L2 device. See kernel API documentation:
> Once an application has allocated the memory buffers needed for streaming data (by calling the ioctl VIDIOC_REQBUFS or ioctl VIDIOC_CREATE_BUFS ioctls, or implicitly by calling the read() or write() functions) that application (filehandle) becomes the owner of the device. It is no longer allowed to make changes that would affect the buffer sizes (e.g. by calling the VIDIOC_S_FMT ioctl) and other applications are no longer allowed to allocate buffers or start or stop streaming. The EBUSY error code will be returned instead.

One is not supposed to make multiple calls to **VIDIOC_REQBUFS** from multiple parties, even it's result does not break your program. Currently you can do this upon v4l2loopback virtual devices because it's an improper implementation. Allowing the behavior you suggested here is going to make it even worse. As pointed out in https://github.com/umlaeute/v4l2loopback/issues/310#issuecomment-633419106, you're going to bump into the same issue now or later.

**Comment by vicamo** [comment]
The right solution should be https://gstreamer.freedesktop.org/documentation/coreelements/tee.html?gi-language=c by the way.

**Comment by umlaeute** [comment]
as of dfe65ebd2de2dd34ee7d8d81154405745be6d200 (and the upcoming v0.13 release), it is no longer allowed to attach multiple (parallel) consumers to a single device.

**Pull request closed without merging**
