### PR TITLE
support v4l2 event apis

### PR DESCRIPTION
**Pull request by vicamo**
This is an attempt to enable V4L2 Events API in v4l2loopback. Now we have:
```
$ v4l2-compliance -v -d /dev/video1
...
        test VIDIOC_(UN)SUBSCRIBE_EVENT/DQEVENT: OK
```

### CODE REVIEW

**Comment by umlaeute** [comment]
which problems does this PR solve?

**Comment by vicamo** [comment]
Hi, this will be a new feature to support V4L2 Event API as [akvcam](https://github.com/webcamoid/akvcam), another v4l2 loopback implementation, does, and at the same time be an attempt to refactor v4l2loopback with in-kernel sub frameworks like v4l2-fh.

**Comment by umlaeute** [comment]
> Hi, this will be a new feature to support V4L2 Event API as akvcam, another v4l2 loopback implementation, does, 

so what is the use-case?

> and at the same time be an attempt to refactor v4l2loopback with in-kernel sub frameworks like v4l2-fh.

i welcome this, however:
- afaict, this is really unrelated to the "event API" feature. it should go into a separate PR (just telling; luckily it seems that all the changes are in separate commit)
- will this work with older kernels as well? (aka: do we need ifdef-protectors for legacy support?)

**Comment by vicamo** [comment]
Rebase on latest develop branch. Tested build old kernels as well. So far 3.16 is the oldest kernel known working, and it fails on 3.13 due to incompatibility introduced by IDR.

So there is a project called [libcamera](https://libcamera.org/), which is to wrap V4L2 and other ways of camera access in a user space library and provide unified API interface. Under libcamera, there is no more directly access to underlying video devices, so a compatible layer based on `LD_PRELOAD` was implemented. However, it introduces additional troubles in security reasons as well as adoption difficulties especially for those container based application packages. So a loopback device that connects both libcamera and traditional V4L2 based applications is the right solution. That's when v4l2loopback/akvcam emerges from the horizon. In order to have better handle of the device states, V4L2 Event API provides an official way to notify both sides.

And since V4L2 Events API is based on v4l2_fh sub framework, and it's automatically achieved by implementations using v4l2_fh, the major task here is to add and use v4l2_fh in the opener structure.

That's the full story. :)

**Pull request merged**
